import { Droplets, MapPinned, Navigation, RadioTower, RefreshCw } from 'lucide-react'
import { useState } from 'react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import AlertCard from '../components/AlertCard'
import EmptyState from '../components/EmptyState'
import IncidentCard from '../components/IncidentCard'
import LoadingState from '../components/LoadingState'
import PageIntro from '../components/PageIntro'
import PriorityCard from '../components/PriorityCard'
import RoadStatusBadge from '../components/RoadStatusBadge'
import SectionHeader from '../components/SectionHeader'
import StatCard from '../components/StatCard'
import { alerts, dashboardStats, incidents, priorities, roads, trendData } from '../data/dashboard'

function Panel({ children, className = '' }) { return <section className={`border border-[#dce5e7] bg-white p-5 shadow-[0_4px_16px_rgba(31,67,80,0.035)] sm:p-6 ${className}`}>{children}</section> }

function RiskOverview() {
  return <Panel className="xl:col-span-2"><SectionHeader eyebrow="Terrain intelligence" title="Current risk overview" action="Open risk map" /><div className="grid gap-5 lg:grid-cols-[1.15fr_0.85fr]"><div className="relative flex min-h-[260px] items-center justify-center overflow-hidden bg-[#dfeceb]"><div className="absolute inset-0 opacity-50" style={{ backgroundImage: 'linear-gradient(30deg, transparent 48%, #80a9a8 49%, transparent 50%), linear-gradient(120deg, transparent 48%, #80a9a8 49%, transparent 50%)', backgroundSize: '54px 54px' }} /><div className="absolute left-[16%] top-[29%] h-5 w-5 rounded-full border-4 border-white bg-[#ef6847] shadow-lg" /><div className="absolute right-[22%] top-[46%] h-5 w-5 rounded-full border-4 border-white bg-[#f0a64a] shadow-lg" /><div className="absolute bottom-[21%] left-[43%] h-5 w-5 rounded-full border-4 border-white bg-[#efc943] shadow-lg" /><div className="absolute bottom-[26%] right-[34%] h-5 w-5 rounded-full border-4 border-white bg-[#3abdb2] shadow-lg" /><div className="relative text-center"><MapPinned size={32} className="mx-auto text-[#ef6847]" /><p className="display-font mt-3 text-lg font-bold text-[#245363]">NER risk layer</p><p className="mt-1 text-xs text-[#5f7d84]">42 districts · 118 monitoring points</p></div></div><div className="space-y-4"><div className="flex items-center justify-between border-b border-[#edf1f2] pb-3"><span className="text-sm text-[#66808a]">Critical exposure</span><span className="display-font text-xl font-bold text-[#d94d35]">08 zones</span></div><div className="flex items-center justify-between border-b border-[#edf1f2] pb-3"><span className="text-sm text-[#66808a]">Rainfall outlook</span><span className="flex items-center gap-1.5 text-sm font-bold text-[#2c7480]"><Droplets size={15} /> 72 mm</span></div><div className="flex items-center justify-between border-b border-[#edf1f2] pb-3"><span className="text-sm text-[#66808a]">Sensor coverage</span><span className="text-sm font-bold text-[#168d84]">94.6%</span></div><div className="flex items-center justify-between"><span className="text-sm text-[#66808a]">Last update</span><span className="text-xs font-bold text-[#80979e]">2 min ago</span></div><div className="flex items-center gap-2 bg-[#e8f7f5] p-3 text-xs font-semibold text-[#27756f]"><RadioTower size={15} /> All monitoring systems operational</div></div></div></Panel>
}

function TrendChart() {
  return <Panel><SectionHeader eyebrow="Weather signal" title="Rainfall / risk trend" action="Last 7 days" /><div className="h-[250px] w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trendData} margin={{ top: 8, right: 2, left: -22, bottom: 0 }}><defs><linearGradient id="rainFill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#3abdb2" stopOpacity={0.28} /><stop offset="95%" stopColor="#3abdb2" stopOpacity={0} /></linearGradient><linearGradient id="riskFill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#ef6847" stopOpacity={0.22} /><stop offset="95%" stopColor="#ef6847" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="#edf1f2" vertical={false} /><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{ fill: '#8aa0a6', fontSize: 11 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: '#8aa0a6', fontSize: 10 }} /><Tooltip contentStyle={{ border: '1px solid #dce5e7', borderRadius: 0, fontSize: 12 }} /><Area type="monotone" dataKey="rainfall" name="Rainfall" stroke="#3abdb2" strokeWidth={2} fill="url(#rainFill)" /><Area type="monotone" dataKey="risk" name="Risk index" stroke="#ef6847" strokeWidth={2} fill="url(#riskFill)" /></AreaChart></ResponsiveContainer></div><div className="mt-2 flex gap-4 text-[11px] font-semibold text-[#718991]"><span className="flex items-center gap-1.5"><span className="h-2 w-2 rounded-full bg-[#3abdb2]" />Rainfall</span><span className="flex items-center gap-1.5"><span className="h-2 w-2 rounded-full bg-[#ef6847]" />Risk index</span></div></Panel>
}

export default function Dashboard() {
  const [isLoading, setIsLoading] = useState(false)
  const runRefresh = () => { setIsLoading(true); window.setTimeout(() => setIsLoading(false), 650) }
  return <div className="page-enter"><PageIntro eyebrow="Operations overview" title="Regional situation room" description="A coordinated view of landslide risk, active incidents and response readiness across the North Eastern Region." action="View live map" /><div className="mb-6 flex items-center justify-between gap-3"><div className="flex items-center gap-2 text-xs text-[#6e8991]"><span className="h-2 w-2 rounded-full bg-[#3abdb2]" />Live command feed · Updated 2 min ago</div><button type="button" onClick={runRefresh} className="flex items-center gap-2 text-xs font-bold text-[#2c7480]" aria-label="Refresh dashboard"><RefreshCw size={14} className={isLoading ? 'animate-spin' : ''} />Refresh</button></div>{isLoading ? <Panel><LoadingState label="Refreshing regional signals" /></Panel> : <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{dashboardStats.map((stat) => <StatCard key={stat.label} {...stat} />)}</div><div className="mt-6 grid gap-6 xl:grid-cols-3"><RiskOverview /><TrendChart /><Panel><SectionHeader eyebrow="Public safety" title="Active disaster alerts" action="View all" /><div>{alerts.length ? alerts.map((alert) => <AlertCard key={alert.title} {...alert} />) : <EmptyState label="No active alerts" />}</div></Panel><Panel><SectionHeader eyebrow="Access network" title="Road connectivity status" action="Road network" /><div className="space-y-4">{roads.length ? roads.map((road) => <div key={road.name} className="flex items-start gap-3 border-b border-[#edf1f2] pb-3 last:border-0 last:pb-0"><Navigation size={16} className="mt-0.5 text-[#70929b]" /><div className="min-w-0 flex-1"><div className="flex flex-wrap justify-between gap-2"><p className="text-sm font-bold text-[#284c58]">{road.name}</p><RoadStatusBadge status={road.status} /></div><p className="mt-1 text-xs text-[#80979e]">{road.detail} · {road.updated}</p></div></div>) : <EmptyState label="No road status data" />}</div></Panel><Panel><SectionHeader eyebrow="Priority queue" title="Emergency priority locations" action="Coordinate response" /><div>{priorities.length ? priorities.map((priority) => <PriorityCard key={priority.title} {...priority} />) : <EmptyState label="No priority locations" />}</div></Panel><Panel className="xl:col-span-2"><SectionHeader eyebrow="Community signal" title="Recent citizen reports" action="View incidents" /><div className="grid gap-3 md:grid-cols-2">{incidents.length ? incidents.map((incident) => <IncidentCard key={incident.title} {...incident} />) : <EmptyState label="No recent reports" />}</div></Panel></div></>}</div>
}