import { AlertTriangle, Play, RotateCcw } from 'lucide-react'
import { useSimulation } from '../context/useSimulation'

function Comparison({ label, normal, simulated, unit = '' }) { return <div className="border border-[#f0d9d2] bg-white p-3"><p className="text-[10px] font-bold uppercase tracking-[0.1em] text-[#8f7770]">{label}</p><p className="mt-2 text-sm font-bold text-[#66808a]"><span>{normal}{unit}</span><span className="mx-2 text-[#ef6847]">→</span><span className="text-[#d94d35]">{simulated}{unit}</span></p></div> }

export default function SimulationPanel() {
  const { status, error, normalValues, simulatedValues, startSimulation, resetSimulation } = useSimulation()
  const isActive = status === 'active'
  return <section className={`mb-6 border p-5 shadow-[0_6px_20px_rgba(31,67,80,0.05)] sm:p-6 ${isActive ? 'border-[#e8c1b8] bg-[#fffaf8]' : 'border-[#cbdcdf] bg-white'}`}><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-start"><div className="flex items-start gap-3"><div className={`flex h-10 w-10 shrink-0 items-center justify-center ${isActive ? 'bg-[#fff0ec] text-[#d94d35]' : 'bg-[#eef5f5] text-[#367985]'}`}><AlertTriangle size={20} /></div><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#ef6847]">Simulation Mode</p><h2 className="display-font mt-1 text-xl font-bold text-[#173747]">Disaster simulation</h2><p className="mt-1 text-xs leading-relaxed text-[#80979e]">Backend-connected heavy rainfall scenario. Values are controlled by FastAPI.</p></div></div><div className="flex flex-wrap gap-2">{!isActive && <button type="button" onClick={startSimulation} disabled={status === 'running'} className="flex items-center gap-2 bg-[#ef6847] px-4 py-3 text-xs font-bold text-white disabled:cursor-wait disabled:opacity-70"><Play size={15} />{status === 'running' ? 'Starting simulation...' : 'Start simulation'}</button>}{isActive && <button type="button" onClick={resetSimulation} disabled={status === 'running'} className="flex items-center gap-2 border border-[#d94d35] px-4 py-3 text-xs font-bold text-[#d94d35]"><RotateCcw size={15} />Reset simulation</button>}</div></div>{error && <div role="alert" className="mt-5 border border-[#e8c1b8] bg-[#fff0ec] p-3 text-xs font-semibold leading-relaxed text-[#b33b2b]">{error}</div>}<div className="mt-5 border-t border-[#edf1f2] pt-5"><div className="mb-4 flex flex-wrap items-center gap-2 text-xs font-bold text-[#66808a]"><span>Normal</span><span className="text-[#9aadb2]">↓ Heavy rainfall → critical response</span>{isActive && <span className="bg-[#fff0ec] px-2 py-1 text-[10px] uppercase tracking-[0.1em] text-[#d94d35]">Scenario active</span>}</div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Comparison label="Rainfall" normal={normalValues.rainfall} simulated={simulatedValues.rainfall} unit=" mm" /><Comparison label="Risk" normal={normalValues.risk} simulated={simulatedValues.risk} unit="%" /><Comparison label="Road" normal={normalValues.roadStatus} simulated={simulatedValues.roadStatus} /><Comparison label="Alerts" normal={normalValues.alerts} simulated={simulatedValues.alerts} /><Comparison label="Priority" normal={normalValues.emergencyPriority} simulated={simulatedValues.emergencyPriority} /></div></div></section>
}