import { Bell, ChevronDown, Search } from 'lucide-react'
import { useLocation } from 'react-router-dom'
import { pageDetails } from '../data/navigation'
import useAppContext from '../context/useAppContext'

export default function Topbar() {
  const { pathname } = useLocation(); const details = pageDetails[pathname] || pageDetails['/dashboard']
  const { locale, setLocale, t } = useAppContext()
  return <header className="border-b border-[#dce5e7] bg-white/90 px-4 py-4 backdrop-blur sm:px-6 lg:px-10"><div className="flex items-center justify-between gap-4 pl-14 lg:pl-0"><div className="min-w-0"><p className="hidden text-[10px] font-bold uppercase tracking-[0.2em] text-[#ef6847] sm:block">{details.eyebrow}</p><h1 className="display-font mt-0.5 truncate text-xl font-bold text-[#173747] sm:text-2xl">{details.title}</h1></div><div className="flex items-center gap-2 sm:gap-4"><div className="hidden items-center gap-2 border border-[#dce5e7] bg-[#f7fafb] px-3 py-2 md:flex"><Search size={16} aria-hidden="true" className="text-[#79939c]" /><input aria-label={t('search')} placeholder={t('search')} className="w-36 bg-transparent text-sm outline-none placeholder:text-[#91a6ad]" /></div><label className="sr-only" htmlFor="language-selector">{t('language')}</label><select id="language-selector" value={locale} onChange={(event) => setLocale(event.target.value)} className="border border-[#dce5e7] bg-white px-2 py-2 text-xs font-bold text-[#4d6872] outline-none focus:border-[#2c7480]" aria-label={t('language')}><option value="en">EN</option><option value="hi">हिं</option></select><button type="button" className="relative flex h-10 w-10 items-center justify-center border border-[#dce5e7] text-[#4d6872]" aria-label={t('notifications')}><Bell size={18} aria-hidden="true" /><span className="absolute right-2 top-2 h-1.5 w-1.5 bg-[#ef6847]" /></button><button type="button" className="hidden items-center gap-3 border-l border-[#dce5e7] pl-4 sm:flex" aria-label="Open user menu"><span className="flex h-9 w-9 items-center justify-center bg-[#d9ece9] text-sm font-bold text-[#17665d]">AS</span><span className="text-left"><span className="block text-xs font-bold text-[#254653]">A. Sharma</span><span className="block text-[10px] text-[#8399a0]">Control room</span></span><ChevronDown size={15} aria-hidden="true" className="text-[#80959c]" /></button></div></div></header>
}